name: ecom
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

#-------------PACKAGES--------------#
dependencies:

  firebase_core: ^2.24.1
  flutter:
    sdk: flutter


  # Utility Packages
  http: ^1.1.2
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.8
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0


  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  





#--------------DEVPACKAGES----------#
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #-----------LOCAL ASSETS----------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/icons/categories/
    - assets/images/on_boarding_images/
    - assets/images/animations/

  #-----------LOCAL FONTS-----------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
