// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWFYcrcVrstJKDhGasIYPWyo5LQEjLyVI',
    appId: '1:38956669503:web:ad83b090f965dfe45bb68a',
    messagingSenderId: '38956669503',
    projectId: 'ecom-c1b51',
    authDomain: 'ecom-c1b51.firebaseapp.com',
    storageBucket: 'ecom-c1b51.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAngwSR6sFAovhfmzaNR2mU1r-lKsTMImo',
    appId: '1:38956669503:android:740db7526dab80535bb68a',
    messagingSenderId: '38956669503',
    projectId: 'ecom-c1b51',
    storageBucket: 'ecom-c1b51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFV4zN5G7I7OooaeKOVdz8ThSH13PzDTo',
    appId: '1:38956669503:ios:779cd31bae08347e5bb68a',
    messagingSenderId: '38956669503',
    projectId: 'ecom-c1b51',
    storageBucket: 'ecom-c1b51.appspot.com',
    androidClientId: '38956669503-l9gujpj9o0e6cf90s6gruv9q6fn1m8ab.apps.googleusercontent.com',
    iosClientId: '38956669503-cvrqogu47hept61gdu06lgdd6q63snnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
  );
}
